plugins {
    id 'com.android.library'
}

android {
    namespace = 'com.kunzisoft.encrypt'
    compileSdk = 36

    defaultConfig {
        minSdk = 34
    }

    buildTypes {
        release {
            minifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    packaging {
        resources {
            pickFirsts += 'META-INF/versions/9/OSGI-INF/MANIFEST.MF'
        }
    }
    lint {
        targetSdk = 36
    }
    testOptions {
        targetSdk = 36
    }
}

dependencies {
    api 'org.bouncycastle:bcpkix-jdk18on:1.84'
}
